/*
 * ini.h
 */

#ifndef INI_H_
#define INI_H_

#define APP_VERSION				"1.0"

#define EXIT_ON_WRONG_FW_DEPENDENCY
#define MIN_DEPEND_FW_VER_MAJOR		3
#define MIN_DEPEND_FW_VER_MINOR		9
#define MIN_DEPEND_FW_VER_BUILD		44

#define EXIT_ON_WRONG_LIB_DEPENDENCY
#define MIN_DEPEND_LIB_VER_MAJOR	4
#define MIN_DEPEND_LIB_VER_MINOR	0
#define MIN_DEPEND_LIB_VER_BUILD	30

#endif /* INI_H_ */
